const topic_name =" M.C.Q. on \"Jimmy Valentine\""; 
const list=[
            "Who wrote the popular short story \"Jimmy Valentine\"?",
	 		"Shakespeare.",
	 		"Rabindranath Tagore.",
	 		"O. Henry.",
	 		"c",
	 
	 
            "Who was popularly known as O. Henry?",
	 		"John Keats.",
	 		"Charles Dickens.",
	 		"William Sydney Porter.",
	 		"c",
	
	        "Where is this short story taken from?",
	 		"David Copperfield.",
	 		"Roads of destiny.",
	 		"Strong Roots.",
	 		"b",
	 		
	 		"At first, Jimmy was in a ",
	 		"Shop.",
	 		"Prison.",
	 		"Saloon.",
	 		"b",
	 		
	 		"Who escorted Jimmy to the front office?",
	 		"a guard.",
	 		"an errand boy.",
	 		"the warden.",
	 		"a",
	 		
	 		"Who handed Jimmy his pardon?",
	 		"The warden.",
	 		"The king.",
	 		"The Bishop.",
	 		"a",
	 		
	 		"Jimmy had served nearly ",
	 		"five months of a four year sentence..",
	 		"ten months of a four year sentence.",
	 		"six months of a four year sentence..",
	 		"b",
	 
	 		"Jimmy had expected to stay in the prison",
	 		"about one month only.",
	 		"about two months.",
	 		"about three months.",
	 		"c",
	 
	 		"The warden advised Jimmy ",
	 		"to stop cracking safes.",
	 		"to stop eating cakes.",
	 		"to stop cracking jokes.",
	 		"a",
	 
	 		"Jimmy was released from the prison",
	 		"at a half past seven on the next morning.",
	 		"at a quarter past seven on the next morning.",
	 		"at a quarter past eight on the next morning.",
	 		"b",
	 
	 		"The clerk handed Jimmy ",
	 		"a railroad ticket and a ten dollar bill.",
	 		"a railroad ticket and a twenty five dollar bill.",
	 		"a railroad ticket and a five dollar bill.",
	 		"c",
	 
	 		"The warden gave Jimmy",
	 		"a cigar.",
	 		"a cigarette.",
	 		"nothing.",
	 		"a",
	 
	 		"Jimmy was the prisoner number",
	 		"9672.",
	 		"9762.",
	 		"9622.",
	 		"b",
	 
	 		"Jimmy went to the cafe of ",
	 		"Mic Donald.",
	 		"Mcdonalds.",
	 		"Mike Dolan.",
	 		"c",
	 
	 		"In his room, Jimmy found the collar-button of",
	 		"Pen Price.",
	 		"Ben Price.",
	 		"his friend.",
	 		"b",
			
			"Jimmy dragged out a ",
	 		"torn shirt.",
	 		"dust-covered suitcase.",
	 		"dust-covered bag.",
	 		"b",  
			
			"The total set of tools cost Jimmy",
	 		"over nine hundred dollars.",
	 		"over five hundred dollars.",
	 		"over four hundred dollars.",
	 		"a",
	
			"Ben Price was a",
	 		"a friend of Jimmy.",
	 		"the hotel owner.",
	 		"famous detective.",
	 		"c",
	
			"After his release from prison, Jimmy's first safe-burglary was done in ",
	 		"Logansport.",
	 		"Richmond, Indiana.",
	 		"Jefferson City.",
	 		"b",
	
			"Jimmy came across Annabel in ",
	 		"Springfield.",
	 		"Elmore  .",
	 		"Jefferson City.",
	 		"b",
		
			"Annabel Adams was the  daughter of ",
	 		"the owner of The Elmore Bank.",
	 		"Jimmy.",
	 		"Polly Simpson.",
	 		"a", 
			
			"At planter's Hotel, Jimmy registered as ",
	 		"a cab driver.",
	 		"shoe seller.",
	 		"Ralph D. Spencer.",
	 		"c",
			
			"At Elmore, Jimmy wanted to start ",
	 		"a jewelery business.",
	 		"a medicine shop.",
	 		"a shoe business.",
	 		"c",
	
			"Jimmy invited his old friend at",
	 		"Planter's hotel.",
	 		"Sullivan's place.",
	 		"a marketplace.",
	 		"b",
	
			"The names of the two children were",
	 		"May and Agatha.",
	 		"May and June.",
	 		"May and Kay.",
	 		"a",
	
			"May was",
	 		"a six-year-old girl.",
	 		"a nine-year-old girl.",
	 		"a five-year-old girl.",
	 		"b", 
	
			"The girl whom Jimmy rescued was",
	 		"May.",
	 		"Annabel.",
	 		"Agatha.",
	 		"c",
	
			"Jimmy rescued Agatha from the safe ",
	 		"within five minutes.",
	 		"within ten minutes.",
	 		"within a minute.",
	 		"b",
	
			"The name of the Banker was",
	 		"Mr. Adams",
	 		"Mr. Spencer.",
	 		"Mr. Bean.",
	 		"a",
			
			"The new vault of The Elmore bank had a",
	 		"painted door.",
	 		"printed door.",
	 		"patented door.",
	 		"c"
        ];
