const topic_name ="The Adventurous Clown"; 
const list=[
            "Who was Tuffy?",
	 		"a toy clown",
	 		"a clown",
	 		"a crown",
	 		"a",
	 
	 
            "Where did Tuffy live?",
	 		"in his school",
	 		"in his friend's house",
	 		"in a toy shop",
	 		"c",
	
	        "What was Tudffy's aim in life?",
	 		"He wanted to play soccer.",
	 		"He wanted to be a hero." ,
	 		"He wanted to eat everything.",
	 		"b",
	 		
	 		"Who was Timothy?",
	 		"a large dog",
	 		"a puppy dog",
	 		"a cat",
	 		"b",
	 		
	 		"Adventures are",
	 		"always exciting.",
	 		"always dull.",
	 		"always boring.",
	 		"a",
	 		
	 		"The grand race was between",
	 		"two wooden horses.",
	 		"two horses.",
	 		"two houses.",
	 		"a",
	 		
	 		"The farmer was  ",
	 		"very happy.",
	 		"furious.",
	 		"to some extent happy.",
	 		"b",
	 
	 		"In his first attempt, Tuffy",
	 		"succeeded.",
	 		"got success.",
	 		"failed.",
	 		"c",
	 
	 		"The farmer called Tuffy",
	 		"silly.",
	 		"jolly.",
	 		"holy.",
	 		"a",
	 
	 		"Tuffy noticed a doll's house on fire.",
	 		"false.",
	 		"true.",
	 		"no idea.",
	 		"b",
	 
	 		"Tuffy found ",
	 		"a hammer.",
	 		"an axe.",
	 		"a ladder.",
	 		"c",
	 
	 		"The sailor doll was making",
	 		"porridge.",
	 		"pudding.",
	 		"pasta.",
	 		"a",
	 
	 		"Tuffy wanted to rescue the small doll",
	 		"from fire.",
	 		"from the big bowl of water.",
	 		"from pyre.",
	 		"b",
	 
	 		"The little doll began to ",
	 		"scold.",
	 		"laugh.",
	 		"cry.",
	 		"c",
	 
	 		"The policeman locked Tuffy",
	 		"in a box.",
	 		"in a room.",
	 		"in a bowl.",
	 		"b",
			
			"Timothy rescued,",
	 		"fluffy.",
	 		"Tuffy.",
	 		"the little doll.",
	 		"b",  
			
			"Tuffy found his shelf",
	 		"very peaceful.",
	 		"very pestering.",
	 		"very noisy.",
	 		"a",
	
			"Tuffy was thankful to Timothy.",
	 		"I don't know.",
	 		"false.",
	 		"true.",
	 		"c",
	
			"Tuffy unlocked the door",
	 		"slowly.",
	 		"quickly.",
	 		"blindly.",
	 		"b",
	
			"Tuffy was always in search of ",
	 		"chocolate.",
	 		"adventure.",
	 		"friends.",
	 		"b",
		
			"Two fine gold fish were swimming",
	 		"in the big bowl of water.",
	 		"in a pond.",
	 		"in the river.",
	 		"a", 
			
			"Timothy told Tuffy ",
	 		"to fight with his friends.",
	 		"to scold his friends.",
	 		"to be happy with his friends.",
	 		"c",
			
			"Tuffy grumbled. So tuffy had  ",
	 		"a pleasing personality.",
	 		" a heroic attitude.",
	 		"a bad temper.",
	 		"c",
	
			"The cart turned over and the farmer",
	 		"fled away.",
	 		"fell down.",
	 		"started to fly.",
	 		"b",
	
			"Tuffy dipped the little net",
	 		"into the water.",
	 		"into the syrup.",
	 		"into icecream.",
	 		"a",
	
			"The word sobbed means",
	 		"sober.",
	 		"cried with little gasps.",
	 		"shocked.",
	 		"b", 
	
			"The key fell to the floor.",
	 		"false.",
	 		"no idea.",
	 		"true.",
	 		"c",
	
			"The little doll thinks Tuffy ",
	 		"is a hero.",
	 		"is not a hero.",
	 		"is a toy.",
	 		"b",
	
			"Enid Blyton was ",
	 		"a British author.",
	 		"an American author.",
	 		"an Indian author.",
	 		"a",
			
			"The adventurous Clown is a ",
	 		"a poem.",
	 		"a play.",
	 		"short story.",
	 		"c"
        ];
