const list = [
    "start", "play", "beautiful", "secret", "honest", "down", "bought", "purchased", "school",
    "sound", "fight", "light", "present", "closed", "table", "window", "summer", "vacation",
    "participate", "attend", "through", "phone", "spaceship", "universe", "tomorrow", "yesterday",
    "night", "goodbye", "welcome", "come", "arrive", "singular", "plural", "person", "crazy", "impress",
    "hungry", "party", "watch", "write", "appear", "absent", "door", "chair", "light", "ceiling",
    "building", "meal", "tiffin", "price", "floor", "touch", "push", "feel", "smile", "cry", "make",
    "mind", "laughter", "sorrow", "blessing", "recess", "regular", "irregular", "together", "lonely",
    "cycle", "student", "guardian", "parent", "father", "mother", "uncle", "aunt", "teacher", "pupil",
    "ground", "lovely", "prayer", "uniform", "dress", "examination", "evaluation", "test", "holiday",
    "cheer", "shout", "chatting", "talking", "shine", "shoulder", "country", "unity", "state", 
    "capital", "senior", "junior", "superior", "inferior", "late", "early", "previous", "sickness", 
    "illness", "cough", "fever", "tension", "memorize", "seems", "confidence,", "about", "absorb", "access", "accident", "actress", "actually", "adapt", "adjustment", "admire", "admission", "workplace.", "learn", "questions", "essential", "learn", "English", "memorize", "seems", "confidence,", "about", "absorb", "access", "accident", "accompany", "according", "achieve", "acknowledge", "acquire", "activity", "actor", "actress", "actually", "adapt", "adjustment", "admire", "admission", "adolescent", "adopt", "advance", "advertising", "advise", "affect", "African-American", "aggressive", "agree", "agricultural", "airport", "album", "almost", "along", "although", "amazing", "among", "amount", "ancient", "anticipate", "anxiety", "apart", "apparent", "apparently", "application", "approach", "approval", "approve", "approximately", "architect", "arise", 
"around", "arrange", "arrive", "assess", "assessment", "asset", "assign", "association","assume", "assumption", "assure", "attack", "attribute", "avoid", "award", "balance", "barely", "baseball", "basically", "basis", "basketball", "bathroom", "battery", "beach", "before", "beginning", "behavior", "below", "beneath", "beside", "besides", "Bible", "blanket", "blind", "blood", "border", "borrow", "bother", "bread", "breakfast", 
"breast", "breath", "bridge", "brief", "bring", "British", "brother", "brush", "budget", "burden", "buyer", "capability", "captain", "carbon", "careful", "carefully", "carry", "cause", "ceiling", "celebration", "celebrity", "center", "century", "ceremony", "certain", "champion", "character", "characterize", "charge", "chase", "Chinese", 
"choice", "circumstance", "civilian", "classic", "clearly", "clinical", "close", "cloud", "coalition", "colleague", "collective", "column", "comment", "commercial", "commitment", "committee", "comparison", "complete", "completely", "condition", "confident", "confirm", "confusion", "congressional", "connect", "consensus", "consequence", "consist", "consumption", "container", "contemporary", "content", "context", "continue", "continued", 
"controversial", "controversy", "convention", "conventional", "conversation", "conviction", 
"cooperation", "correspondent", "cotton", "couch", "could", "counter", "courage", 
"crack", "craft", "crazy", "create", "creation", "criminal", "critical", "cross", 
"cultural", "curriculum", "cycle", "decide", "decision", "delay", "deliver", "Democrat", 
"democratic", "department", "dependent", "depression", "depth", "deserve", "design", 
"designer", "detail", "determine", "develop", "device", "digital", "dimension", "dinner", 
"disappear", "disease", "disorder", "distinction", "divorce", "doctor", "double", 
"dramatically", "drawing", "dress", "drink", "drive", "driver", "eager", "earnings", 
"earth", "economic", "economics", "economist", "effect", "efficiency", "efficient", 
"effort", "electric", "element", "elementary", "eliminate", "emergency", "emphasis", 
"employee", "employment", "enable", "encourage", "enemy", "enforcement", "engage", 
"engineer", "enhance", "enjoy", "entire", "equal", "error", "especially", "essay", 
"essential", "estate", "ethnic", "European", "evaluate", "event", "every", "everybody", 
"evolution", "examination", "examine", "exceed", "except", "exception", "exercise", 
"exist", "expansion", "expect", "expectation", "extension", "extra", "extraordinary", 
"fabric", "factor", "factory", "fantasy", "fashion", "feature", "feeling", "female", 
"fiction", "fifteen", "fighting", "figure", "finally", "financial", "finding", "flame", 
"formation", "forth", "foundation", "founder", "fourth", "framework", "freeze", "French", 
"frequently", "fresh", "friend", "friendly", "fruit", "frustration", "fully", "function", 
"funding", "funny", "furthermore", "gallery", "garage", "garlic", "gently", "gesture", 
"giant", "global", "grade", "graduate", "grant", "grave", "grocery", "guarantee", 
"habit", "handle", "healthy", "heavily", "helicopter", "highlight", "highly", "historian", 
"horse", "however", "human", "humor", "hundred", "husband", "identity", "illegal", 
"illness", "image", "immediate", "immigrant", "imply", "importance", "important", 
"impose", "impress", "improvement", "increase", "increased", "increasingly", "independent", 
"index", "indication", "initial", "initially", "injury", "inner", "insight", "inspire", 
"instrument", "intend", "intensity", "interest", "interview", "introduce", "invest", 
"investigate", "involve", "Iraqi", "issue", "jacket", "Japanese", "joint", "journal", 
"kitchen", "knowledge", "labor", "language", "lawsuit", "layer", "leader", "leadership", 
"leading", "least", "legal", "legend", "legitimate", "lemon", "lifestyle", "limited", 
"literature", "living", "local", "locate", "location", "long-term", "loose", "lovely", 
"lover", "lucky", "lunch", "machine", "manage", "manager", "married", "marry", "match", 
"mechanism", "member", "memory", "mention", "merely", "message", "metal", "meter", 
"might", "minister", "minor", "minority", "miracle", "mm-hmm", "model", "modern", 
"month", "moral", "moreover", "motion", "mount", "mouth", "movement", "musician", 
"mutual", "naturally", "nature", "nearby", "nearly", "necessarily", "necessary", 
"negotiate", "neighbor", "neither", "nervous", "network", "noise", "north", "northern", 
"nowhere", "nuclear", "numerous", "obligation", "obvious", "occasionally", "occur", 
"offense", "offensive", "often", "opening", "operation", "operator", "orange", "order", 
"ordinary", "organic", "organize", "origin", "original", "originally", "overcome", 
"overlook", "painter", "parking", "participant", "participation", "party", "passenger", 
"patch", "pattern", "payment", "penalty", "percentage", "performance", "personality", 
"personally", "persuade", "physically", "place", "pleasure", "point", "policy", "porch", 
"portion", "possible", "pound", "powerful", "practice", "pregnancy", "presence", 
"presidential", "pretty", "priest", "primary", "prime", "prior", "privacy", "problem", 
"proceed", "production", "profession", "profile", "program", "project", "prominent", 
"promise", "property", "proportion", "prospect", "protection", "protest", "prove", 
"psychological", "psychology", "public", "publication", "publicly", "publish", "purpose", 
"pursue", "question", "quickly", "quiet", "quietly", "radical", "raise", "rapid", 
"rather", "ratio", "react", "really", "recovery", "reference", "reform", "regarding", 
"regime", "regular", "regulate", "reinforce", "relatively", "religious", "remaining", 
"remote", "replace", "reply", "represent", "requirement", "resemble", "resolution", 
"resolve", "resort", "responsibility", "restaurant", "restriction", "result", "retirement", 
"rifle", "river", "romantic", "rough", "roughly", "Russian", "safety", "salary", 
"sales", "sample", "scared", "scenario", "schedule", "scholar", "science", "scientist", 
"scream", "screen", "script", "select", "Senate", "separate", "series", "serious", 
"service", "session", "shell", "shirt", "shock", "shortly", "sight", "signal", "silent", 
"silver", "similarly", "situation", "skill", "slightly", "small", "smile", "so-called", 
"society", "solution", "something", "sorry", "sound", "southern", "Spanish", "special", 
"specialist", "split", "square", "stability", "stage", "stair", "stand", "standard", 
"standing", "stare", "start", "station", "statistics", "steal", "storage", "store", 
"story", "straight", "strategic", "strategy", "street", "stretch", "string", "strip", 
"strong", "structure", "study", "substantial", "suddenly", "suffer", "sugar", "support", 
"surface", "surprise", "surprised", "surprisingly", "survey", "survival", "suspect", 
"symbol", "table", "tactic", "talent", "teaching", "teaspoon", "technique", "technology", 
"telescope", "terrible", "terror", "testify", "theater", "theme", "themselves", "therapy", 
"there", "therefore", "these", "thick", "thing", "thinking", "throat", "throw", "tobacco", 
"tough", "tournament", "trace", "tradition", "transform", "travel", "treat", "tremendous", 
"trick", "typical", "under", "undergo", "uniform", "universe", "unlike", "unlikely", 
"upper", "useful", "usual", "valley", "variable", "versus", "victory", "violence", 
"visit", "vital", "voice", "warning", "weekend", "weekly", "whatever", "wheel", "whenever", 
"whether", "white", "window", "wisdom", "within", "wonder", "working", "works", "workshop", 
"worry", "write", "writer", "yellow", "yours", "yourself", "understand", "words", "Vocabulary"  
    
];