const topic_name ="The Shop That Never Was"; 
const list=[
            "Who was H.G.Wells?",
	 		"a story teller",
	 		"a dramatist",
	 		"a famous English Science Fiction writer",
	 		"c",
	 
	 
            "Who dragged the author up to the magic shop?",
	 		"his daughter",
	 		"the shop keeper",
	 		"his son, Gip",
	 		"c",
	
	        "The magic shop was",
	 		"very big but not well lit.",
	 		"a little narrow and not well lit.",
	 		"large and well lit.",
	 		"b",
	 		
	 		"On the floor, there were",
	 		"glass tiles",
	 		"magic mirrors",
	 		"nice carpets",
	 		"b",
	 		
	 		"What was the price of the glass ball?",
	 		"It was free.",
	 		"It was costly.",
	 		"It was not pricey.",
	 		"a",
	 		
	 		"Gip found the glass ball",
	 		"in his pocket.",
	 		"in his box.",
	 		"inside his palm.",
	 		"a",
	 		
	 		"Gip wanted to buy a  ",
	 		"magic doll.",
	 		"magic box.",
	 		"magic mirror.",
	 		"b",
	 
	 		"The shopman invited the author to visit ",
	 		"magic factory.",
	 		"magic castle.",
	 		"their showroom.",
	 		"c",
	 
	 		"The magic toy sword ",
	 		"was unique.",
	 		"was just another simple toy.",
	 		"was not that unique.",
	 		"a",
	 
	 		"The magic train ",
	 		"runs with steam.",
	 		"runs without steam.",
	 		"does not run at all.",
	 		"b",
	 
	 		"The box was tied up",
	 		"in white paper.",
	 		"in red paper.",
	 		"in brown paper.",
	 		"c",
	 
	 		"Gip was playing",
	 		"hide and seek.",
	 		"yard twister.",
	 		"hula hoop.",
	 		"a",
	 
	 		"The author told the shopman",
	 		"to continue the game.",
	 		"to take the big drum off.",
	 		"to frighten Gip.",
	 		"b",
	 
	 		"The author found himself",
	 		"in an unknown place.",
	 		"in a faraway place.",
	 		"in Regent Street.",
	 		"c",
	 
	 		"Gip was carrying",
	 		"only on parcel.",
	 		"four parcels.",
	 		"two parcels.",
	 		"b",
			
			"Gip, the son of the author,",
	 		"looked scared.",
	 		"did not look scared.",
	 		"looked disturbed.",
	 		"b",  
			
			"The author",
	 		"had not paid for the items.",
	 		"paid for the items.",
	 		"refused to pay for the items.",
	 		"a",
	
			"The author called for ",
	 		"his car.",
	 		"a bus.",
	 		"a cab.",
	 		"c",
	
			"Gip was standing on",
	 		"a chair.",
	 		"a stool.",
	 		"a bench.",
	 		"b",
	
			"The shopman was holding",
	 		"a small drum.",
	 		"a big drum.",
	 		"a jug.",
	 		"b",
		
			"Gip was",
	 		"very impressed with that magic shop.",
	 		"upset with that magic shop.",
	 		"indifferent with that magic shop.",
	 		"a", 
			
			"The box of soldiers came alive",
	 		"automatically.",
	 		"when one remained silent.",
	 		"when one said a magic word.",
	 		"c",
			
			"The narrator was",
	 		"very happy.",
	 		"excited.",
	 		"at a loss.",
	 		"c",
	
			"The narrator could not find",
	 		"the window of the magic shop.",
	 		"the door of the magic shop.",
	 		"the floor of the magic shop.",
	 		"b",
	
			"The author collided",
	 		"with a man.",
	 		"with Gip.",
	 		"with a stray dog.",
	 		"a",
	
			"The narrator wanted to buy",
	 		"many things from that magic shop.",
	 		"a few simple tricks.",
	 		"nothing.",
	 		"b", 
	
			"The shopman drew the glass ball",
	 		"from his pocekt.",
	 		"from his bag.",
	 		"from his hair.",
	 		"c",
	
			"The shopman drew the business card ",
	 		"from his bag.",
	 		"from his cheek.",
	 		"from his hair.",
	 		"b",
	
			"The magic trick showed by the shopman was",
	 		"unexpected.",
	 		"expected.",
	 		"bad.",
	 		"a",
			
			"The narrator ",
	 		"trusted the shopman.",
	 		"was indifferent to the shopman.",
	 		"did not trust the shopman.",
	 		"c"
        ];
