const topic_name ="Buildings to Remember"; 
const list=[
            "Mita and her friends went to Bandel with",
	 		"the History teacher.",
	 		"the English teacher.",
	 		"the Games teacher.",
	 		"a",
	 
	 
            "The team began their journey from",
	 		"Belur.",
	 		"Bandel.",
	 		"Chandannagar.",
	 		"c",
	
	        "Amina was",
	 		"a neighbour of Mita.",
            "the sister of Mita.",
	 		"a friend of Mita.",
	 		"c",
	 		
	 		"The Portuguese began to use Bandel ",
	 		"as a church.",
	 		"as a port.",
	 		"as a village.",
	 		"b",
	 		
	 		"Akbar gave the Portuguese a permission",
	 		"to build a town.",
	 		"to build a ship.",
	 		"to build a church.",
	 		"a",
	 		
	 		"The Bandel church was built",
	 		"in 1599.",
	 		"in 1699.",
	 		"in 1799.",
	 		"a",
	 		
	 		"Augustinians were the ",
	 		"people who were born in August.",
	 		"followers of Saint Augustine.",
	 		"people from India.",
	 		"b",
	 
	 		"The Mughal siege ",
	 		"built the Bandel church.",
	 		"did not harm the church.",
	 		"destroyed the Bandel church.",
	 		"c",
	 
	 		"Father Joan da Cruz",
	 		"was the priest of the Bandel church.",
	 		"was a commoner.",
	 		"was not a religious man.",
	 		"a",
	 
	 		"At first, Shahjahan ordered ",
	 		" to release the prisoners.",
	 		" to punish the prisoners.",
	 		" to set the prisoners free.",
	 		"b",
	 
	 		"The elephant was.",
	 		"hungry.",
	 		"tired.",
	 		"ferocious.",
	 		"c",
	 
	 		"Shah Jahan was impressed by the",
            "act of the elephant.",
	 		"personality of the priest.",
	 		"power of the Portuguese people.",
	 		"a",
	 
	 		"Shah Jahan granted money",
	 		"to destroy the church.",
	 		"to reconstruct the church.",
	 		"to kill all the Portuguese people.",
	 		"b",
	 
	 		"The Bandel church was modified and reconstructed",
	 		"only once.",
	 		"only twice.",
	 		"several times.",
	 		"c",
	 
	 		"In the Bandel church, there is a statue of",
	 		"a Mermaid.",
	 		"Mother Mary.",
	 		"the Mother Nature.",
	 		"b",
			
			"The huge clock has",
	 		"two faces.",
	 		"four faces.",
	 		"only one face.",
	 		"b",  
			
			"At the end of the day, the students felt",
	 		"happy and enriched.",
	 		"exhausted.",
	 		"that they learnt nothing.",
	 		"a",
	
			"The visit to the Bandel church",
	 		"was not a rewarding trip.",
	 		"went in vain.",
	 		"was a rewarding trip.",
	 		"c",
	
			"The children were",
	 		"not interested.",
	 		"eager and disciplined.",
	 		"not impressed.",
	 		"b",
	
			"The teacher ",
	 		"did not explain anything to the eager students.",
	 		"explained to the eager students.",
	 		"was not interested.",
	 		"b",
		
			"A cemetery is",
	 		"a place where dead bodies are buried.",
	 		"a cement factory.",
	 		"a show of symmetry.",
	 		"a", 
			
			"The mast is ",
	 		"a mask.",
	 		"a must have thing.",
	 		"a tall post of a ship carrying a sail.",
	 		"c",
			
			"The word elated means",
	 		"upset.",
	 		"depressed.",
	 		"overjoyed.",
	 		"c",
	
			"Agra is a ",
	 		"port.",
	 		"fort.",
	 		"boat.",
	 		"b",
	
			"The bus stopped",
	 		"in front of the church.",
	 		"all on a sudden.",
	 		"and didn't move again.",
	 		"a",
	
			"A church is related to",
	 		"Hindu religion.",
	 		"the Christian religion.",
	 		"a religion named Islam.",
	 		"b", 
	
			"Outing means",
	 		"going outside.",
	 		"getting a batsman out in cricket.",
	 		"a short trip.",
	 		"c",
	
			"Monk stands for ",
	 		"a man who is not pious.",
	 		"a religious man.",
	 		"a man who hates religion.",
	 		"b",
	
			"We should visit a place",
	 		"for fun, enjoyment and enrichment.",
	 		"to spend our money and show off.",
	 		"to go shopping and take photos.",
	 		"a",
			
			"The history of the Bandel church is some",
	 		"150 years old.",
	 		"100 years old.",
	 		"450 years old.",
	 		"c"
        ];
