const topic_name ="ALL SUMMER IN A DAY"; 
const list=[
            "Ray Douglas Bradbury was one of the most ",
	 		"celebrated American fiction writers.",
	 		"famous poets.",
	 		"famous American playwrights.",
	 		"a",
	 
	 
            "The days were filled with",
	 		"endless sun rays.",
	 		"endless fun.",
	 		"gush of water and endless showers.",
	 		"c",
	
	        "Heavy storms caused",
	 		"dire dilapidation of the planet Venus.",
            "the capsizing.",
	 		"tidal waves.",
	 		"c",
	 		
	 		"The resident of Venus set up a",
	 		"a pandemonium.",
	 		"civilization.",
	 		"village.",
	 		"b",
	 		
	 		"The students looked through the window",
	 		"for the hidden sun.",
	 		"for the hidden moon.",
	 		"for the hidden earth.",
	 		"a",
	 		
	 		"The children were",
	 		"nine years old.",
	 		"twelve years old.",
	 		"three years old.",
	 		"a",
	 		
	 		"The sun came out last time",
	 		"five years ago.",
	 		"seven years ago.",
	 		"three years ago.",
	 		"b",
	 
	 		"The sun came out",
	 		"for seven days.",
	 		"for a day only.",
	 		"for just an hour.",
	 		"c",
	 
	 		"The last appearance of the sun",
	 		"stunned the Venus.",
	 		"stunned the earth.",
	 		"stunned the moon.",
	 		"a",
	 
	 		"In the class yesterday, the students had read",
	 		" about the earth.",
	 		" about the sun.",
	 		" about the moon.",
	 		"b",
	 
	 		"The rain slackened.",
	 		"Slackened means continued.",
	 		"Slackened means started.",
	 		"Slackened means slowed down.",
	 		"c",
	 
	 		"The children were eager",
            "to see the sun.",
	 		"to play hide and seek.",
	 		"to play yard twister.",
	 		"a",
	 
	 		"The children had forgotten",
	 		"the colour and heat of the Venus.",
	 		"the colour and heat of the sun.",
	 		"the colour and heat of the earth.",
	 		"b",
	 
	 		"In Venus, people lived in ",
	 		"a wide-open area.",
	 		"an extremely cold place.",
	 		"an underground city.",
	 		"c",
	 
	 		"The kids sang of",
	 		"the earth.",
	 		"summer and sun.",
	 		"winter and moon.",
	 		"b",
			
			"The sun appeared in,",
	 		"the typical winter.",
	 		"the summertime.",
	 		"the wildest dream.",
	 		"b",  
			
			"What was the colour of the sun? ",
	 		"flaming bronze",
	 		"orange",
	 		"pale.",
	 		"a",
	
			"The sky around the sun was ",
	 		"overcast with thick black clouds.",
	 		"all black.",
	 		"blazing blue.",
	 		"c",
	
			"The children felt that the sunlight",
	 		"was cold.",
	 		"was much better than the lamplight.",
	 		"was not impressive.",
	 		"b",
	
			"The teacher forbade the kids",
	 		"to go far.",
	 		"to go too far.",
	 		"to play.",
	 		"b",
		
			"The children were",
	 		"ecstatic at the appearance of the sun.",
	 		"upset at the emergence of the sun.",
	 		"indifferent to the visible sun.",
	 		"a", 
			
			"The children breathed the ",
	 		"polluted air.",
	 		"air full of toxic fumes.",
	 		"fresh air.",
	 		"c",
			
			"The children listened to the",
	 		"noises.",
	 		"hustle and bustle around them.",
	 		"blessed silence.",
	 		"c",
	
			"The children savoured",
	 		"their captivity.",
	 		"the freedom and ecstasy.",
	 		"the gloomy atmosphere.",
	 		"b",
	
			"The children ran and played for",
	 		"an hour.",
	 		"a day.",
	 		"a week.",
	 		"a",
	
			"The girl began to cry",
	 		"looking at the sea.",
	 		"looking at the large rain drop.",
	 		"without any valid reason.",
	 		"b", 
	
			"The sun faded behind ",
	 		"the hill.",
	 		"the jungle.",
	 		"a cloud of mist.",
	 		"c",
	
			"A boom of thunder",
	 		"made the children cry.",
	 		"startled the children.",
	 		"made the children sad.",
	 		"b",
	
			"The sound of rain falling was",
	 		"gigantic.",
	 		"soothing.",
	 		"almost inaudible.",
	 		"a",
			
			"The sun will come out again ",
	 		"after three years.",
	 		"after four years.",
	 		"after seven years.",
	 		"c"
        ];
